// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/example_proto_fast_parsing_test.proto

#include "tensorflow/core/util/example_proto_fast_parsing_test.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_tensorflow_2fcore_2fexample_2ffeature_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Features_tensorflow_2fcore_2fexample_2ffeature_2eproto;
namespace tensorflow {
class ExampleWithExtrasDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ExampleWithExtras> _instance;
} _ExampleWithExtras_default_instance_;
}  // namespace tensorflow
static void InitDefaultsscc_info_ExampleWithExtras_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tensorflow::_ExampleWithExtras_default_instance_;
    new (ptr) ::tensorflow::ExampleWithExtras();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tensorflow::ExampleWithExtras::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ExampleWithExtras_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ExampleWithExtras_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto}, {
      &scc_info_Features_tensorflow_2fcore_2fexample_2ffeature_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, features_),
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, extra1_),
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, extra2_),
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, extra3_),
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, extra4_),
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, extra5_),
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, extra6_),
  PROTOBUF_FIELD_OFFSET(::tensorflow::ExampleWithExtras, extra7_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tensorflow::ExampleWithExtras)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tensorflow::_ExampleWithExtras_default_instance_),
};

const char descriptor_table_protodef_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n:tensorflow/core/util/example_proto_fas"
  "t_parsing_test.proto\022\ntensorflow\032%tensor"
  "flow/core/example/feature.proto\"\310\001\n\021Exam"
  "pleWithExtras\022&\n\010features\030\001 \001(\0132\024.tensor"
  "flow.Features\022\017\n\006extra1\030\271\n \001(\t\022\017\n\006extra2"
  "\030\272\n \001(\003\022\017\n\006extra3\030\273\n \001(\007\022\017\n\006extra4\030\274\n \001("
  "\006\022\017\n\006extra5\030\275\n \001(\001\022\017\n\006extra6\030\276\n \003(\002\022%\n\006e"
  "xtra7\030\277\n \001(\0132\024.tensorflow.FeaturesB\003\370\001\001b"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto_deps[1] = {
  &::descriptor_table_tensorflow_2fcore_2fexample_2ffeature_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto_sccs[1] = {
  &scc_info_ExampleWithExtras_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto_once;
static bool descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto = {
  &descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto_initialized, descriptor_table_protodef_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto, "tensorflow/core/util/example_proto_fast_parsing_test.proto", 327,
  &descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto_once, descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto_sccs, descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto::offsets,
  file_level_metadata_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto, 1, file_level_enum_descriptors_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto, file_level_service_descriptors_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto), true);
namespace tensorflow {

// ===================================================================

void ExampleWithExtras::InitAsDefaultInstance() {
  ::tensorflow::_ExampleWithExtras_default_instance_._instance.get_mutable()->features_ = const_cast< ::tensorflow::Features*>(
      ::tensorflow::Features::internal_default_instance());
  ::tensorflow::_ExampleWithExtras_default_instance_._instance.get_mutable()->extra7_ = const_cast< ::tensorflow::Features*>(
      ::tensorflow::Features::internal_default_instance());
}
class ExampleWithExtras::_Internal {
 public:
  static const ::tensorflow::Features& features(const ExampleWithExtras* msg);
  static const ::tensorflow::Features& extra7(const ExampleWithExtras* msg);
};

const ::tensorflow::Features&
ExampleWithExtras::_Internal::features(const ExampleWithExtras* msg) {
  return *msg->features_;
}
const ::tensorflow::Features&
ExampleWithExtras::_Internal::extra7(const ExampleWithExtras* msg) {
  return *msg->extra7_;
}
void ExampleWithExtras::unsafe_arena_set_allocated_features(
    ::tensorflow::Features* features) {
  if (GetArenaNoVirtual() == nullptr) {
    delete features_;
  }
  features_ = features;
  if (features) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.ExampleWithExtras.features)
}
void ExampleWithExtras::clear_features() {
  if (GetArenaNoVirtual() == nullptr && features_ != nullptr) {
    delete features_;
  }
  features_ = nullptr;
}
void ExampleWithExtras::unsafe_arena_set_allocated_extra7(
    ::tensorflow::Features* extra7) {
  if (GetArenaNoVirtual() == nullptr) {
    delete extra7_;
  }
  extra7_ = extra7;
  if (extra7) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.ExampleWithExtras.extra7)
}
void ExampleWithExtras::clear_extra7() {
  if (GetArenaNoVirtual() == nullptr && extra7_ != nullptr) {
    delete extra7_;
  }
  extra7_ = nullptr;
}
ExampleWithExtras::ExampleWithExtras()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.ExampleWithExtras)
}
ExampleWithExtras::ExampleWithExtras(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
  _internal_metadata_(arena),
  extra6_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.ExampleWithExtras)
}
ExampleWithExtras::ExampleWithExtras(const ExampleWithExtras& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      extra6_(from.extra6_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  extra1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_extra1().empty()) {
    extra1_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_extra1(),
      GetArenaNoVirtual());
  }
  if (from._internal_has_features()) {
    features_ = new ::tensorflow::Features(*from.features_);
  } else {
    features_ = nullptr;
  }
  if (from._internal_has_extra7()) {
    extra7_ = new ::tensorflow::Features(*from.extra7_);
  } else {
    extra7_ = nullptr;
  }
  ::memcpy(&extra3_, &from.extra3_,
    static_cast<size_t>(reinterpret_cast<char*>(&extra5_) -
    reinterpret_cast<char*>(&extra3_)) + sizeof(extra5_));
  // @@protoc_insertion_point(copy_constructor:tensorflow.ExampleWithExtras)
}

void ExampleWithExtras::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ExampleWithExtras_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto.base);
  extra1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&features_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&extra5_) -
      reinterpret_cast<char*>(&features_)) + sizeof(extra5_));
}

ExampleWithExtras::~ExampleWithExtras() {
  // @@protoc_insertion_point(destructor:tensorflow.ExampleWithExtras)
  SharedDtor();
}

void ExampleWithExtras::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == nullptr);
  extra1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete features_;
  if (this != internal_default_instance()) delete extra7_;
}

void ExampleWithExtras::ArenaDtor(void* object) {
  ExampleWithExtras* _this = reinterpret_cast< ExampleWithExtras* >(object);
  (void)_this;
}
void ExampleWithExtras::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ExampleWithExtras::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ExampleWithExtras& ExampleWithExtras::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ExampleWithExtras_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto.base);
  return *internal_default_instance();
}


void ExampleWithExtras::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.ExampleWithExtras)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  extra6_.Clear();
  extra1_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  if (GetArenaNoVirtual() == nullptr && features_ != nullptr) {
    delete features_;
  }
  features_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && extra7_ != nullptr) {
    delete extra7_;
  }
  extra7_ = nullptr;
  ::memset(&extra3_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&extra5_) -
      reinterpret_cast<char*>(&extra3_)) + sizeof(extra5_));
  _internal_metadata_.Clear();
}

const char* ExampleWithExtras::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArenaNoVirtual(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .tensorflow.Features features = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_features(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string extra1 = 1337;
      case 1337:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 202)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(_internal_mutable_extra1(), ptr, ctx, "tensorflow.ExampleWithExtras.extra1");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 extra2 = 1338;
      case 1338:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 208)) {
          extra2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // fixed32 extra3 = 1339;
      case 1339:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 221)) {
          extra3_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint32>(ptr);
          ptr += sizeof(::PROTOBUF_NAMESPACE_ID::uint32);
        } else goto handle_unusual;
        continue;
      // fixed64 extra4 = 1340;
      case 1340:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 225)) {
          extra4_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint64>(ptr);
          ptr += sizeof(::PROTOBUF_NAMESPACE_ID::uint64);
        } else goto handle_unusual;
        continue;
      // double extra5 = 1341;
      case 1341:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 233)) {
          extra5_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated float extra6 = 1342;
      case 1342:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 242)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_extra6(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 245) {
          _internal_add_extra6(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // .tensorflow.Features extra7 = 1343;
      case 1343:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 250)) {
          ptr = ctx->ParseMessage(_internal_mutable_extra7(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ExampleWithExtras::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.ExampleWithExtras)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tensorflow.Features features = 1;
  if (this->has_features()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::features(this), target, stream);
  }

  // string extra1 = 1337;
  if (this->extra1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_extra1().data(), static_cast<int>(this->_internal_extra1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tensorflow.ExampleWithExtras.extra1");
    target = stream->WriteStringMaybeAliased(
        1337, this->_internal_extra1(), target);
  }

  // int64 extra2 = 1338;
  if (this->extra2() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1338, this->_internal_extra2(), target);
  }

  // fixed32 extra3 = 1339;
  if (this->extra3() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFixed32ToArray(1339, this->_internal_extra3(), target);
  }

  // fixed64 extra4 = 1340;
  if (this->extra4() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFixed64ToArray(1340, this->_internal_extra4(), target);
  }

  // double extra5 = 1341;
  if (!(this->extra5() <= 0 && this->extra5() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1341, this->_internal_extra5(), target);
  }

  // repeated float extra6 = 1342;
  if (this->_internal_extra6_size() > 0) {
    target = stream->WriteFixedPacked(1342, _internal_extra6(), target);
  }

  // .tensorflow.Features extra7 = 1343;
  if (this->has_extra7()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1343, _Internal::extra7(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.ExampleWithExtras)
  return target;
}

size_t ExampleWithExtras::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.ExampleWithExtras)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float extra6 = 1342;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_extra6_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _extra6_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string extra1 = 1337;
  if (this->extra1().size() > 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_extra1());
  }

  // .tensorflow.Features features = 1;
  if (this->has_features()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *features_);
  }

  // .tensorflow.Features extra7 = 1343;
  if (this->has_extra7()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *extra7_);
  }

  // fixed32 extra3 = 1339;
  if (this->extra3() != 0) {
    total_size += 2 + 4;
  }

  // int64 extra2 = 1338;
  if (this->extra2() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_extra2());
  }

  // fixed64 extra4 = 1340;
  if (this->extra4() != 0) {
    total_size += 2 + 8;
  }

  // double extra5 = 1341;
  if (!(this->extra5() <= 0 && this->extra5() >= 0)) {
    total_size += 2 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExampleWithExtras::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.ExampleWithExtras)
  GOOGLE_DCHECK_NE(&from, this);
  const ExampleWithExtras* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ExampleWithExtras>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.ExampleWithExtras)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.ExampleWithExtras)
    MergeFrom(*source);
  }
}

void ExampleWithExtras::MergeFrom(const ExampleWithExtras& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.ExampleWithExtras)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  extra6_.MergeFrom(from.extra6_);
  if (from.extra1().size() > 0) {
    _internal_set_extra1(from._internal_extra1());
  }
  if (from.has_features()) {
    _internal_mutable_features()->::tensorflow::Features::MergeFrom(from._internal_features());
  }
  if (from.has_extra7()) {
    _internal_mutable_extra7()->::tensorflow::Features::MergeFrom(from._internal_extra7());
  }
  if (from.extra3() != 0) {
    _internal_set_extra3(from._internal_extra3());
  }
  if (from.extra2() != 0) {
    _internal_set_extra2(from._internal_extra2());
  }
  if (from.extra4() != 0) {
    _internal_set_extra4(from._internal_extra4());
  }
  if (!(from.extra5() <= 0 && from.extra5() >= 0)) {
    _internal_set_extra5(from._internal_extra5());
  }
}

void ExampleWithExtras::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.ExampleWithExtras)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExampleWithExtras::CopyFrom(const ExampleWithExtras& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.ExampleWithExtras)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExampleWithExtras::IsInitialized() const {
  return true;
}

void ExampleWithExtras::InternalSwap(ExampleWithExtras* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  extra6_.InternalSwap(&other->extra6_);
  extra1_.Swap(&other->extra1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(features_, other->features_);
  swap(extra7_, other->extra7_);
  swap(extra3_, other->extra3_);
  swap(extra2_, other->extra2_);
  swap(extra4_, other->extra4_);
  swap(extra5_, other->extra5_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ExampleWithExtras::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tensorflow
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tensorflow::ExampleWithExtras* Arena::CreateMaybeMessage< ::tensorflow::ExampleWithExtras >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorflow::ExampleWithExtras >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
