// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/lite/toco/toco_flags.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/lite/toco/types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto;
namespace toco {
class TocoFlags;
class TocoFlagsDefaultTypeInternal;
extern TocoFlagsDefaultTypeInternal _TocoFlags_default_instance_;
}  // namespace toco
PROTOBUF_NAMESPACE_OPEN
template<> ::toco::TocoFlags* Arena::CreateMaybeMessage<::toco::TocoFlags>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace toco {

enum FileFormat : int {
  FILE_FORMAT_UNKNOWN = 0,
  TENSORFLOW_GRAPHDEF = 1,
  TFLITE = 2,
  GRAPHVIZ_DOT = 3
};
bool FileFormat_IsValid(int value);
constexpr FileFormat FileFormat_MIN = FILE_FORMAT_UNKNOWN;
constexpr FileFormat FileFormat_MAX = GRAPHVIZ_DOT;
constexpr int FileFormat_ARRAYSIZE = FileFormat_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FileFormat_descriptor();
template<typename T>
inline const std::string& FileFormat_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FileFormat>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FileFormat_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FileFormat_descriptor(), enum_t_value);
}
inline bool FileFormat_Parse(
    const std::string& name, FileFormat* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FileFormat>(
    FileFormat_descriptor(), name, value);
}
// ===================================================================

class TocoFlags :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:toco.TocoFlags) */ {
 public:
  TocoFlags();
  virtual ~TocoFlags();

  TocoFlags(const TocoFlags& from);
  TocoFlags(TocoFlags&& from) noexcept
    : TocoFlags() {
    *this = ::std::move(from);
  }

  inline TocoFlags& operator=(const TocoFlags& from) {
    CopyFrom(from);
    return *this;
  }
  inline TocoFlags& operator=(TocoFlags&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TocoFlags& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TocoFlags* internal_default_instance() {
    return reinterpret_cast<const TocoFlags*>(
               &_TocoFlags_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TocoFlags& a, TocoFlags& b) {
    a.Swap(&b);
  }
  inline void Swap(TocoFlags* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TocoFlags* New() const final {
    return CreateMaybeMessage<TocoFlags>(nullptr);
  }

  TocoFlags* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TocoFlags>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TocoFlags& from);
  void MergeFrom(const TocoFlags& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TocoFlags* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "toco.TocoFlags";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto);
    return ::descriptor_table_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCustomOpdefsFieldNumber = 32,
    kDumpGraphvizDirFieldNumber = 24,
    kConversionSummaryDirFieldNumber = 31,
    kInputFormatFieldNumber = 1,
    kOutputFormatFieldNumber = 2,
    kInferenceTypeFieldNumber = 4,
    kDefaultRangesMinFieldNumber = 5,
    kDefaultRangesMaxFieldNumber = 6,
    kDropFakeQuantFieldNumber = 7,
    kReorderAcrossFakeQuantFieldNumber = 8,
    kAllowCustomOpsFieldNumber = 10,
    kDropControlDependencyFieldNumber = 12,
    kInferenceInputTypeFieldNumber = 11,
    kDefaultInt16RangesMinFieldNumber = 15,
    kDefaultInt16RangesMaxFieldNumber = 16,
    kDebugDisableRecurrentCellFusionFieldNumber = 13,
    kPropagateFakeQuantNumBitsFieldNumber = 14,
    kAllowNudgingWeightsToUseFastGemmKernelFieldNumber = 17,
    kQuantizeWeightsFieldNumber = 20,
    kDumpGraphvizIncludeVideoFieldNumber = 25,
    kPostTrainingQuantizeFieldNumber = 26,
    kEnableSelectTfOpsFieldNumber = 27,
    kForceSelectTfOpsFieldNumber = 28,
    kQuantizeToFloat16FieldNumber = 29,
    kSplitTfliteLstmInputsFieldNumber = 19,
    kAllowDynamicTensorsFieldNumber = 30,
    kDedupeArrayMinSizeBytesFieldNumber = 18,
  };
  // repeated string custom_opdefs = 32;
  int custom_opdefs_size() const;
  private:
  int _internal_custom_opdefs_size() const;
  public:
  void clear_custom_opdefs();
  const std::string& custom_opdefs(int index) const;
  std::string* mutable_custom_opdefs(int index);
  void set_custom_opdefs(int index, const std::string& value);
  void set_custom_opdefs(int index, std::string&& value);
  void set_custom_opdefs(int index, const char* value);
  void set_custom_opdefs(int index, const char* value, size_t size);
  std::string* add_custom_opdefs();
  void add_custom_opdefs(const std::string& value);
  void add_custom_opdefs(std::string&& value);
  void add_custom_opdefs(const char* value);
  void add_custom_opdefs(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& custom_opdefs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_custom_opdefs();
  private:
  const std::string& _internal_custom_opdefs(int index) const;
  std::string* _internal_add_custom_opdefs();
  public:

  // optional string dump_graphviz_dir = 24;
  bool has_dump_graphviz_dir() const;
  private:
  bool _internal_has_dump_graphviz_dir() const;
  public:
  void clear_dump_graphviz_dir();
  const std::string& dump_graphviz_dir() const;
  void set_dump_graphviz_dir(const std::string& value);
  void set_dump_graphviz_dir(std::string&& value);
  void set_dump_graphviz_dir(const char* value);
  void set_dump_graphviz_dir(const char* value, size_t size);
  std::string* mutable_dump_graphviz_dir();
  std::string* release_dump_graphviz_dir();
  void set_allocated_dump_graphviz_dir(std::string* dump_graphviz_dir);
  private:
  const std::string& _internal_dump_graphviz_dir() const;
  void _internal_set_dump_graphviz_dir(const std::string& value);
  std::string* _internal_mutable_dump_graphviz_dir();
  public:

  // optional string conversion_summary_dir = 31;
  bool has_conversion_summary_dir() const;
  private:
  bool _internal_has_conversion_summary_dir() const;
  public:
  void clear_conversion_summary_dir();
  const std::string& conversion_summary_dir() const;
  void set_conversion_summary_dir(const std::string& value);
  void set_conversion_summary_dir(std::string&& value);
  void set_conversion_summary_dir(const char* value);
  void set_conversion_summary_dir(const char* value, size_t size);
  std::string* mutable_conversion_summary_dir();
  std::string* release_conversion_summary_dir();
  void set_allocated_conversion_summary_dir(std::string* conversion_summary_dir);
  private:
  const std::string& _internal_conversion_summary_dir() const;
  void _internal_set_conversion_summary_dir(const std::string& value);
  std::string* _internal_mutable_conversion_summary_dir();
  public:

  // optional .toco.FileFormat input_format = 1;
  bool has_input_format() const;
  private:
  bool _internal_has_input_format() const;
  public:
  void clear_input_format();
  ::toco::FileFormat input_format() const;
  void set_input_format(::toco::FileFormat value);
  private:
  ::toco::FileFormat _internal_input_format() const;
  void _internal_set_input_format(::toco::FileFormat value);
  public:

  // optional .toco.FileFormat output_format = 2;
  bool has_output_format() const;
  private:
  bool _internal_has_output_format() const;
  public:
  void clear_output_format();
  ::toco::FileFormat output_format() const;
  void set_output_format(::toco::FileFormat value);
  private:
  ::toco::FileFormat _internal_output_format() const;
  void _internal_set_output_format(::toco::FileFormat value);
  public:

  // optional .toco.IODataType inference_type = 4;
  bool has_inference_type() const;
  private:
  bool _internal_has_inference_type() const;
  public:
  void clear_inference_type();
  ::toco::IODataType inference_type() const;
  void set_inference_type(::toco::IODataType value);
  private:
  ::toco::IODataType _internal_inference_type() const;
  void _internal_set_inference_type(::toco::IODataType value);
  public:

  // optional float default_ranges_min = 5;
  bool has_default_ranges_min() const;
  private:
  bool _internal_has_default_ranges_min() const;
  public:
  void clear_default_ranges_min();
  float default_ranges_min() const;
  void set_default_ranges_min(float value);
  private:
  float _internal_default_ranges_min() const;
  void _internal_set_default_ranges_min(float value);
  public:

  // optional float default_ranges_max = 6;
  bool has_default_ranges_max() const;
  private:
  bool _internal_has_default_ranges_max() const;
  public:
  void clear_default_ranges_max();
  float default_ranges_max() const;
  void set_default_ranges_max(float value);
  private:
  float _internal_default_ranges_max() const;
  void _internal_set_default_ranges_max(float value);
  public:

  // optional bool drop_fake_quant = 7;
  bool has_drop_fake_quant() const;
  private:
  bool _internal_has_drop_fake_quant() const;
  public:
  void clear_drop_fake_quant();
  bool drop_fake_quant() const;
  void set_drop_fake_quant(bool value);
  private:
  bool _internal_drop_fake_quant() const;
  void _internal_set_drop_fake_quant(bool value);
  public:

  // optional bool reorder_across_fake_quant = 8;
  bool has_reorder_across_fake_quant() const;
  private:
  bool _internal_has_reorder_across_fake_quant() const;
  public:
  void clear_reorder_across_fake_quant();
  bool reorder_across_fake_quant() const;
  void set_reorder_across_fake_quant(bool value);
  private:
  bool _internal_reorder_across_fake_quant() const;
  void _internal_set_reorder_across_fake_quant(bool value);
  public:

  // optional bool allow_custom_ops = 10;
  bool has_allow_custom_ops() const;
  private:
  bool _internal_has_allow_custom_ops() const;
  public:
  void clear_allow_custom_ops();
  bool allow_custom_ops() const;
  void set_allow_custom_ops(bool value);
  private:
  bool _internal_allow_custom_ops() const;
  void _internal_set_allow_custom_ops(bool value);
  public:

  // optional bool drop_control_dependency = 12;
  bool has_drop_control_dependency() const;
  private:
  bool _internal_has_drop_control_dependency() const;
  public:
  void clear_drop_control_dependency();
  bool drop_control_dependency() const;
  void set_drop_control_dependency(bool value);
  private:
  bool _internal_drop_control_dependency() const;
  void _internal_set_drop_control_dependency(bool value);
  public:

  // optional .toco.IODataType inference_input_type = 11;
  bool has_inference_input_type() const;
  private:
  bool _internal_has_inference_input_type() const;
  public:
  void clear_inference_input_type();
  ::toco::IODataType inference_input_type() const;
  void set_inference_input_type(::toco::IODataType value);
  private:
  ::toco::IODataType _internal_inference_input_type() const;
  void _internal_set_inference_input_type(::toco::IODataType value);
  public:

  // optional float default_int16_ranges_min = 15;
  bool has_default_int16_ranges_min() const;
  private:
  bool _internal_has_default_int16_ranges_min() const;
  public:
  void clear_default_int16_ranges_min();
  float default_int16_ranges_min() const;
  void set_default_int16_ranges_min(float value);
  private:
  float _internal_default_int16_ranges_min() const;
  void _internal_set_default_int16_ranges_min(float value);
  public:

  // optional float default_int16_ranges_max = 16;
  bool has_default_int16_ranges_max() const;
  private:
  bool _internal_has_default_int16_ranges_max() const;
  public:
  void clear_default_int16_ranges_max();
  float default_int16_ranges_max() const;
  void set_default_int16_ranges_max(float value);
  private:
  float _internal_default_int16_ranges_max() const;
  void _internal_set_default_int16_ranges_max(float value);
  public:

  // optional bool debug_disable_recurrent_cell_fusion = 13;
  bool has_debug_disable_recurrent_cell_fusion() const;
  private:
  bool _internal_has_debug_disable_recurrent_cell_fusion() const;
  public:
  void clear_debug_disable_recurrent_cell_fusion();
  bool debug_disable_recurrent_cell_fusion() const;
  void set_debug_disable_recurrent_cell_fusion(bool value);
  private:
  bool _internal_debug_disable_recurrent_cell_fusion() const;
  void _internal_set_debug_disable_recurrent_cell_fusion(bool value);
  public:

  // optional bool propagate_fake_quant_num_bits = 14;
  bool has_propagate_fake_quant_num_bits() const;
  private:
  bool _internal_has_propagate_fake_quant_num_bits() const;
  public:
  void clear_propagate_fake_quant_num_bits();
  bool propagate_fake_quant_num_bits() const;
  void set_propagate_fake_quant_num_bits(bool value);
  private:
  bool _internal_propagate_fake_quant_num_bits() const;
  void _internal_set_propagate_fake_quant_num_bits(bool value);
  public:

  // optional bool allow_nudging_weights_to_use_fast_gemm_kernel = 17;
  bool has_allow_nudging_weights_to_use_fast_gemm_kernel() const;
  private:
  bool _internal_has_allow_nudging_weights_to_use_fast_gemm_kernel() const;
  public:
  void clear_allow_nudging_weights_to_use_fast_gemm_kernel();
  bool allow_nudging_weights_to_use_fast_gemm_kernel() const;
  void set_allow_nudging_weights_to_use_fast_gemm_kernel(bool value);
  private:
  bool _internal_allow_nudging_weights_to_use_fast_gemm_kernel() const;
  void _internal_set_allow_nudging_weights_to_use_fast_gemm_kernel(bool value);
  public:

  // optional bool quantize_weights = 20 [default = false];
  bool has_quantize_weights() const;
  private:
  bool _internal_has_quantize_weights() const;
  public:
  void clear_quantize_weights();
  bool quantize_weights() const;
  void set_quantize_weights(bool value);
  private:
  bool _internal_quantize_weights() const;
  void _internal_set_quantize_weights(bool value);
  public:

  // optional bool dump_graphviz_include_video = 25;
  bool has_dump_graphviz_include_video() const;
  private:
  bool _internal_has_dump_graphviz_include_video() const;
  public:
  void clear_dump_graphviz_include_video();
  bool dump_graphviz_include_video() const;
  void set_dump_graphviz_include_video(bool value);
  private:
  bool _internal_dump_graphviz_include_video() const;
  void _internal_set_dump_graphviz_include_video(bool value);
  public:

  // optional bool post_training_quantize = 26 [default = false];
  bool has_post_training_quantize() const;
  private:
  bool _internal_has_post_training_quantize() const;
  public:
  void clear_post_training_quantize();
  bool post_training_quantize() const;
  void set_post_training_quantize(bool value);
  private:
  bool _internal_post_training_quantize() const;
  void _internal_set_post_training_quantize(bool value);
  public:

  // optional bool enable_select_tf_ops = 27 [default = false];
  bool has_enable_select_tf_ops() const;
  private:
  bool _internal_has_enable_select_tf_ops() const;
  public:
  void clear_enable_select_tf_ops();
  bool enable_select_tf_ops() const;
  void set_enable_select_tf_ops(bool value);
  private:
  bool _internal_enable_select_tf_ops() const;
  void _internal_set_enable_select_tf_ops(bool value);
  public:

  // optional bool force_select_tf_ops = 28 [default = false];
  bool has_force_select_tf_ops() const;
  private:
  bool _internal_has_force_select_tf_ops() const;
  public:
  void clear_force_select_tf_ops();
  bool force_select_tf_ops() const;
  void set_force_select_tf_ops(bool value);
  private:
  bool _internal_force_select_tf_ops() const;
  void _internal_set_force_select_tf_ops(bool value);
  public:

  // optional bool quantize_to_float16 = 29 [default = false];
  bool has_quantize_to_float16() const;
  private:
  bool _internal_has_quantize_to_float16() const;
  public:
  void clear_quantize_to_float16();
  bool quantize_to_float16() const;
  void set_quantize_to_float16(bool value);
  private:
  bool _internal_quantize_to_float16() const;
  void _internal_set_quantize_to_float16(bool value);
  public:

  // optional bool split_tflite_lstm_inputs = 19 [default = true];
  bool has_split_tflite_lstm_inputs() const;
  private:
  bool _internal_has_split_tflite_lstm_inputs() const;
  public:
  void clear_split_tflite_lstm_inputs();
  bool split_tflite_lstm_inputs() const;
  void set_split_tflite_lstm_inputs(bool value);
  private:
  bool _internal_split_tflite_lstm_inputs() const;
  void _internal_set_split_tflite_lstm_inputs(bool value);
  public:

  // optional bool allow_dynamic_tensors = 30 [default = true];
  bool has_allow_dynamic_tensors() const;
  private:
  bool _internal_has_allow_dynamic_tensors() const;
  public:
  void clear_allow_dynamic_tensors();
  bool allow_dynamic_tensors() const;
  void set_allow_dynamic_tensors(bool value);
  private:
  bool _internal_allow_dynamic_tensors() const;
  void _internal_set_allow_dynamic_tensors(bool value);
  public:

  // optional int64 dedupe_array_min_size_bytes = 18 [default = 64];
  bool has_dedupe_array_min_size_bytes() const;
  private:
  bool _internal_has_dedupe_array_min_size_bytes() const;
  public:
  void clear_dedupe_array_min_size_bytes();
  ::PROTOBUF_NAMESPACE_ID::int64 dedupe_array_min_size_bytes() const;
  void set_dedupe_array_min_size_bytes(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_dedupe_array_min_size_bytes() const;
  void _internal_set_dedupe_array_min_size_bytes(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:toco.TocoFlags)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> custom_opdefs_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dump_graphviz_dir_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr conversion_summary_dir_;
  int input_format_;
  int output_format_;
  int inference_type_;
  float default_ranges_min_;
  float default_ranges_max_;
  bool drop_fake_quant_;
  bool reorder_across_fake_quant_;
  bool allow_custom_ops_;
  bool drop_control_dependency_;
  int inference_input_type_;
  float default_int16_ranges_min_;
  float default_int16_ranges_max_;
  bool debug_disable_recurrent_cell_fusion_;
  bool propagate_fake_quant_num_bits_;
  bool allow_nudging_weights_to_use_fast_gemm_kernel_;
  bool quantize_weights_;
  bool dump_graphviz_include_video_;
  bool post_training_quantize_;
  bool enable_select_tf_ops_;
  bool force_select_tf_ops_;
  bool quantize_to_float16_;
  bool split_tflite_lstm_inputs_;
  bool allow_dynamic_tensors_;
  ::PROTOBUF_NAMESPACE_ID::int64 dedupe_array_min_size_bytes_;
  friend struct ::TableStruct_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TocoFlags

// optional .toco.FileFormat input_format = 1;
inline bool TocoFlags::_internal_has_input_format() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TocoFlags::has_input_format() const {
  return _internal_has_input_format();
}
inline void TocoFlags::clear_input_format() {
  input_format_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::toco::FileFormat TocoFlags::_internal_input_format() const {
  return static_cast< ::toco::FileFormat >(input_format_);
}
inline ::toco::FileFormat TocoFlags::input_format() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.input_format)
  return _internal_input_format();
}
inline void TocoFlags::_internal_set_input_format(::toco::FileFormat value) {
  assert(::toco::FileFormat_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  input_format_ = value;
}
inline void TocoFlags::set_input_format(::toco::FileFormat value) {
  _internal_set_input_format(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.input_format)
}

// optional .toco.FileFormat output_format = 2;
inline bool TocoFlags::_internal_has_output_format() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool TocoFlags::has_output_format() const {
  return _internal_has_output_format();
}
inline void TocoFlags::clear_output_format() {
  output_format_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::toco::FileFormat TocoFlags::_internal_output_format() const {
  return static_cast< ::toco::FileFormat >(output_format_);
}
inline ::toco::FileFormat TocoFlags::output_format() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.output_format)
  return _internal_output_format();
}
inline void TocoFlags::_internal_set_output_format(::toco::FileFormat value) {
  assert(::toco::FileFormat_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  output_format_ = value;
}
inline void TocoFlags::set_output_format(::toco::FileFormat value) {
  _internal_set_output_format(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.output_format)
}

// optional .toco.IODataType inference_input_type = 11;
inline bool TocoFlags::_internal_has_inference_input_type() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool TocoFlags::has_inference_input_type() const {
  return _internal_has_inference_input_type();
}
inline void TocoFlags::clear_inference_input_type() {
  inference_input_type_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::toco::IODataType TocoFlags::_internal_inference_input_type() const {
  return static_cast< ::toco::IODataType >(inference_input_type_);
}
inline ::toco::IODataType TocoFlags::inference_input_type() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.inference_input_type)
  return _internal_inference_input_type();
}
inline void TocoFlags::_internal_set_inference_input_type(::toco::IODataType value) {
  assert(::toco::IODataType_IsValid(value));
  _has_bits_[0] |= 0x00000800u;
  inference_input_type_ = value;
}
inline void TocoFlags::set_inference_input_type(::toco::IODataType value) {
  _internal_set_inference_input_type(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.inference_input_type)
}

// optional .toco.IODataType inference_type = 4;
inline bool TocoFlags::_internal_has_inference_type() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool TocoFlags::has_inference_type() const {
  return _internal_has_inference_type();
}
inline void TocoFlags::clear_inference_type() {
  inference_type_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::toco::IODataType TocoFlags::_internal_inference_type() const {
  return static_cast< ::toco::IODataType >(inference_type_);
}
inline ::toco::IODataType TocoFlags::inference_type() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.inference_type)
  return _internal_inference_type();
}
inline void TocoFlags::_internal_set_inference_type(::toco::IODataType value) {
  assert(::toco::IODataType_IsValid(value));
  _has_bits_[0] |= 0x00000010u;
  inference_type_ = value;
}
inline void TocoFlags::set_inference_type(::toco::IODataType value) {
  _internal_set_inference_type(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.inference_type)
}

// optional float default_ranges_min = 5;
inline bool TocoFlags::_internal_has_default_ranges_min() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool TocoFlags::has_default_ranges_min() const {
  return _internal_has_default_ranges_min();
}
inline void TocoFlags::clear_default_ranges_min() {
  default_ranges_min_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline float TocoFlags::_internal_default_ranges_min() const {
  return default_ranges_min_;
}
inline float TocoFlags::default_ranges_min() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.default_ranges_min)
  return _internal_default_ranges_min();
}
inline void TocoFlags::_internal_set_default_ranges_min(float value) {
  _has_bits_[0] |= 0x00000020u;
  default_ranges_min_ = value;
}
inline void TocoFlags::set_default_ranges_min(float value) {
  _internal_set_default_ranges_min(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.default_ranges_min)
}

// optional float default_ranges_max = 6;
inline bool TocoFlags::_internal_has_default_ranges_max() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool TocoFlags::has_default_ranges_max() const {
  return _internal_has_default_ranges_max();
}
inline void TocoFlags::clear_default_ranges_max() {
  default_ranges_max_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline float TocoFlags::_internal_default_ranges_max() const {
  return default_ranges_max_;
}
inline float TocoFlags::default_ranges_max() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.default_ranges_max)
  return _internal_default_ranges_max();
}
inline void TocoFlags::_internal_set_default_ranges_max(float value) {
  _has_bits_[0] |= 0x00000040u;
  default_ranges_max_ = value;
}
inline void TocoFlags::set_default_ranges_max(float value) {
  _internal_set_default_ranges_max(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.default_ranges_max)
}

// optional float default_int16_ranges_min = 15;
inline bool TocoFlags::_internal_has_default_int16_ranges_min() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool TocoFlags::has_default_int16_ranges_min() const {
  return _internal_has_default_int16_ranges_min();
}
inline void TocoFlags::clear_default_int16_ranges_min() {
  default_int16_ranges_min_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline float TocoFlags::_internal_default_int16_ranges_min() const {
  return default_int16_ranges_min_;
}
inline float TocoFlags::default_int16_ranges_min() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.default_int16_ranges_min)
  return _internal_default_int16_ranges_min();
}
inline void TocoFlags::_internal_set_default_int16_ranges_min(float value) {
  _has_bits_[0] |= 0x00001000u;
  default_int16_ranges_min_ = value;
}
inline void TocoFlags::set_default_int16_ranges_min(float value) {
  _internal_set_default_int16_ranges_min(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.default_int16_ranges_min)
}

// optional float default_int16_ranges_max = 16;
inline bool TocoFlags::_internal_has_default_int16_ranges_max() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool TocoFlags::has_default_int16_ranges_max() const {
  return _internal_has_default_int16_ranges_max();
}
inline void TocoFlags::clear_default_int16_ranges_max() {
  default_int16_ranges_max_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline float TocoFlags::_internal_default_int16_ranges_max() const {
  return default_int16_ranges_max_;
}
inline float TocoFlags::default_int16_ranges_max() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.default_int16_ranges_max)
  return _internal_default_int16_ranges_max();
}
inline void TocoFlags::_internal_set_default_int16_ranges_max(float value) {
  _has_bits_[0] |= 0x00002000u;
  default_int16_ranges_max_ = value;
}
inline void TocoFlags::set_default_int16_ranges_max(float value) {
  _internal_set_default_int16_ranges_max(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.default_int16_ranges_max)
}

// optional bool drop_fake_quant = 7;
inline bool TocoFlags::_internal_has_drop_fake_quant() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool TocoFlags::has_drop_fake_quant() const {
  return _internal_has_drop_fake_quant();
}
inline void TocoFlags::clear_drop_fake_quant() {
  drop_fake_quant_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool TocoFlags::_internal_drop_fake_quant() const {
  return drop_fake_quant_;
}
inline bool TocoFlags::drop_fake_quant() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.drop_fake_quant)
  return _internal_drop_fake_quant();
}
inline void TocoFlags::_internal_set_drop_fake_quant(bool value) {
  _has_bits_[0] |= 0x00000080u;
  drop_fake_quant_ = value;
}
inline void TocoFlags::set_drop_fake_quant(bool value) {
  _internal_set_drop_fake_quant(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.drop_fake_quant)
}

// optional bool reorder_across_fake_quant = 8;
inline bool TocoFlags::_internal_has_reorder_across_fake_quant() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool TocoFlags::has_reorder_across_fake_quant() const {
  return _internal_has_reorder_across_fake_quant();
}
inline void TocoFlags::clear_reorder_across_fake_quant() {
  reorder_across_fake_quant_ = false;
  _has_bits_[0] &= ~0x00000100u;
}
inline bool TocoFlags::_internal_reorder_across_fake_quant() const {
  return reorder_across_fake_quant_;
}
inline bool TocoFlags::reorder_across_fake_quant() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.reorder_across_fake_quant)
  return _internal_reorder_across_fake_quant();
}
inline void TocoFlags::_internal_set_reorder_across_fake_quant(bool value) {
  _has_bits_[0] |= 0x00000100u;
  reorder_across_fake_quant_ = value;
}
inline void TocoFlags::set_reorder_across_fake_quant(bool value) {
  _internal_set_reorder_across_fake_quant(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.reorder_across_fake_quant)
}

// optional bool allow_custom_ops = 10;
inline bool TocoFlags::_internal_has_allow_custom_ops() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool TocoFlags::has_allow_custom_ops() const {
  return _internal_has_allow_custom_ops();
}
inline void TocoFlags::clear_allow_custom_ops() {
  allow_custom_ops_ = false;
  _has_bits_[0] &= ~0x00000200u;
}
inline bool TocoFlags::_internal_allow_custom_ops() const {
  return allow_custom_ops_;
}
inline bool TocoFlags::allow_custom_ops() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.allow_custom_ops)
  return _internal_allow_custom_ops();
}
inline void TocoFlags::_internal_set_allow_custom_ops(bool value) {
  _has_bits_[0] |= 0x00000200u;
  allow_custom_ops_ = value;
}
inline void TocoFlags::set_allow_custom_ops(bool value) {
  _internal_set_allow_custom_ops(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.allow_custom_ops)
}

// optional bool drop_control_dependency = 12;
inline bool TocoFlags::_internal_has_drop_control_dependency() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool TocoFlags::has_drop_control_dependency() const {
  return _internal_has_drop_control_dependency();
}
inline void TocoFlags::clear_drop_control_dependency() {
  drop_control_dependency_ = false;
  _has_bits_[0] &= ~0x00000400u;
}
inline bool TocoFlags::_internal_drop_control_dependency() const {
  return drop_control_dependency_;
}
inline bool TocoFlags::drop_control_dependency() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.drop_control_dependency)
  return _internal_drop_control_dependency();
}
inline void TocoFlags::_internal_set_drop_control_dependency(bool value) {
  _has_bits_[0] |= 0x00000400u;
  drop_control_dependency_ = value;
}
inline void TocoFlags::set_drop_control_dependency(bool value) {
  _internal_set_drop_control_dependency(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.drop_control_dependency)
}

// optional bool debug_disable_recurrent_cell_fusion = 13;
inline bool TocoFlags::_internal_has_debug_disable_recurrent_cell_fusion() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool TocoFlags::has_debug_disable_recurrent_cell_fusion() const {
  return _internal_has_debug_disable_recurrent_cell_fusion();
}
inline void TocoFlags::clear_debug_disable_recurrent_cell_fusion() {
  debug_disable_recurrent_cell_fusion_ = false;
  _has_bits_[0] &= ~0x00004000u;
}
inline bool TocoFlags::_internal_debug_disable_recurrent_cell_fusion() const {
  return debug_disable_recurrent_cell_fusion_;
}
inline bool TocoFlags::debug_disable_recurrent_cell_fusion() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.debug_disable_recurrent_cell_fusion)
  return _internal_debug_disable_recurrent_cell_fusion();
}
inline void TocoFlags::_internal_set_debug_disable_recurrent_cell_fusion(bool value) {
  _has_bits_[0] |= 0x00004000u;
  debug_disable_recurrent_cell_fusion_ = value;
}
inline void TocoFlags::set_debug_disable_recurrent_cell_fusion(bool value) {
  _internal_set_debug_disable_recurrent_cell_fusion(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.debug_disable_recurrent_cell_fusion)
}

// optional bool propagate_fake_quant_num_bits = 14;
inline bool TocoFlags::_internal_has_propagate_fake_quant_num_bits() const {
  bool value = (_has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool TocoFlags::has_propagate_fake_quant_num_bits() const {
  return _internal_has_propagate_fake_quant_num_bits();
}
inline void TocoFlags::clear_propagate_fake_quant_num_bits() {
  propagate_fake_quant_num_bits_ = false;
  _has_bits_[0] &= ~0x00008000u;
}
inline bool TocoFlags::_internal_propagate_fake_quant_num_bits() const {
  return propagate_fake_quant_num_bits_;
}
inline bool TocoFlags::propagate_fake_quant_num_bits() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.propagate_fake_quant_num_bits)
  return _internal_propagate_fake_quant_num_bits();
}
inline void TocoFlags::_internal_set_propagate_fake_quant_num_bits(bool value) {
  _has_bits_[0] |= 0x00008000u;
  propagate_fake_quant_num_bits_ = value;
}
inline void TocoFlags::set_propagate_fake_quant_num_bits(bool value) {
  _internal_set_propagate_fake_quant_num_bits(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.propagate_fake_quant_num_bits)
}

// optional bool allow_nudging_weights_to_use_fast_gemm_kernel = 17;
inline bool TocoFlags::_internal_has_allow_nudging_weights_to_use_fast_gemm_kernel() const {
  bool value = (_has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline bool TocoFlags::has_allow_nudging_weights_to_use_fast_gemm_kernel() const {
  return _internal_has_allow_nudging_weights_to_use_fast_gemm_kernel();
}
inline void TocoFlags::clear_allow_nudging_weights_to_use_fast_gemm_kernel() {
  allow_nudging_weights_to_use_fast_gemm_kernel_ = false;
  _has_bits_[0] &= ~0x00010000u;
}
inline bool TocoFlags::_internal_allow_nudging_weights_to_use_fast_gemm_kernel() const {
  return allow_nudging_weights_to_use_fast_gemm_kernel_;
}
inline bool TocoFlags::allow_nudging_weights_to_use_fast_gemm_kernel() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.allow_nudging_weights_to_use_fast_gemm_kernel)
  return _internal_allow_nudging_weights_to_use_fast_gemm_kernel();
}
inline void TocoFlags::_internal_set_allow_nudging_weights_to_use_fast_gemm_kernel(bool value) {
  _has_bits_[0] |= 0x00010000u;
  allow_nudging_weights_to_use_fast_gemm_kernel_ = value;
}
inline void TocoFlags::set_allow_nudging_weights_to_use_fast_gemm_kernel(bool value) {
  _internal_set_allow_nudging_weights_to_use_fast_gemm_kernel(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.allow_nudging_weights_to_use_fast_gemm_kernel)
}

// optional int64 dedupe_array_min_size_bytes = 18 [default = 64];
inline bool TocoFlags::_internal_has_dedupe_array_min_size_bytes() const {
  bool value = (_has_bits_[0] & 0x02000000u) != 0;
  return value;
}
inline bool TocoFlags::has_dedupe_array_min_size_bytes() const {
  return _internal_has_dedupe_array_min_size_bytes();
}
inline void TocoFlags::clear_dedupe_array_min_size_bytes() {
  dedupe_array_min_size_bytes_ = PROTOBUF_LONGLONG(64);
  _has_bits_[0] &= ~0x02000000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TocoFlags::_internal_dedupe_array_min_size_bytes() const {
  return dedupe_array_min_size_bytes_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TocoFlags::dedupe_array_min_size_bytes() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.dedupe_array_min_size_bytes)
  return _internal_dedupe_array_min_size_bytes();
}
inline void TocoFlags::_internal_set_dedupe_array_min_size_bytes(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x02000000u;
  dedupe_array_min_size_bytes_ = value;
}
inline void TocoFlags::set_dedupe_array_min_size_bytes(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_dedupe_array_min_size_bytes(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.dedupe_array_min_size_bytes)
}

// optional bool split_tflite_lstm_inputs = 19 [default = true];
inline bool TocoFlags::_internal_has_split_tflite_lstm_inputs() const {
  bool value = (_has_bits_[0] & 0x00800000u) != 0;
  return value;
}
inline bool TocoFlags::has_split_tflite_lstm_inputs() const {
  return _internal_has_split_tflite_lstm_inputs();
}
inline void TocoFlags::clear_split_tflite_lstm_inputs() {
  split_tflite_lstm_inputs_ = true;
  _has_bits_[0] &= ~0x00800000u;
}
inline bool TocoFlags::_internal_split_tflite_lstm_inputs() const {
  return split_tflite_lstm_inputs_;
}
inline bool TocoFlags::split_tflite_lstm_inputs() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.split_tflite_lstm_inputs)
  return _internal_split_tflite_lstm_inputs();
}
inline void TocoFlags::_internal_set_split_tflite_lstm_inputs(bool value) {
  _has_bits_[0] |= 0x00800000u;
  split_tflite_lstm_inputs_ = value;
}
inline void TocoFlags::set_split_tflite_lstm_inputs(bool value) {
  _internal_set_split_tflite_lstm_inputs(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.split_tflite_lstm_inputs)
}

// optional bool quantize_weights = 20 [default = false];
inline bool TocoFlags::_internal_has_quantize_weights() const {
  bool value = (_has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline bool TocoFlags::has_quantize_weights() const {
  return _internal_has_quantize_weights();
}
inline void TocoFlags::clear_quantize_weights() {
  quantize_weights_ = false;
  _has_bits_[0] &= ~0x00020000u;
}
inline bool TocoFlags::_internal_quantize_weights() const {
  return quantize_weights_;
}
inline bool TocoFlags::quantize_weights() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.quantize_weights)
  return _internal_quantize_weights();
}
inline void TocoFlags::_internal_set_quantize_weights(bool value) {
  _has_bits_[0] |= 0x00020000u;
  quantize_weights_ = value;
}
inline void TocoFlags::set_quantize_weights(bool value) {
  _internal_set_quantize_weights(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.quantize_weights)
}

// optional string dump_graphviz_dir = 24;
inline bool TocoFlags::_internal_has_dump_graphviz_dir() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TocoFlags::has_dump_graphviz_dir() const {
  return _internal_has_dump_graphviz_dir();
}
inline void TocoFlags::clear_dump_graphviz_dir() {
  dump_graphviz_dir_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TocoFlags::dump_graphviz_dir() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.dump_graphviz_dir)
  return _internal_dump_graphviz_dir();
}
inline void TocoFlags::set_dump_graphviz_dir(const std::string& value) {
  _internal_set_dump_graphviz_dir(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.dump_graphviz_dir)
}
inline std::string* TocoFlags::mutable_dump_graphviz_dir() {
  // @@protoc_insertion_point(field_mutable:toco.TocoFlags.dump_graphviz_dir)
  return _internal_mutable_dump_graphviz_dir();
}
inline const std::string& TocoFlags::_internal_dump_graphviz_dir() const {
  return dump_graphviz_dir_.GetNoArena();
}
inline void TocoFlags::_internal_set_dump_graphviz_dir(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  dump_graphviz_dir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TocoFlags::set_dump_graphviz_dir(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  dump_graphviz_dir_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:toco.TocoFlags.dump_graphviz_dir)
}
inline void TocoFlags::set_dump_graphviz_dir(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  dump_graphviz_dir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:toco.TocoFlags.dump_graphviz_dir)
}
inline void TocoFlags::set_dump_graphviz_dir(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  dump_graphviz_dir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:toco.TocoFlags.dump_graphviz_dir)
}
inline std::string* TocoFlags::_internal_mutable_dump_graphviz_dir() {
  _has_bits_[0] |= 0x00000001u;
  return dump_graphviz_dir_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TocoFlags::release_dump_graphviz_dir() {
  // @@protoc_insertion_point(field_release:toco.TocoFlags.dump_graphviz_dir)
  if (!has_dump_graphviz_dir()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return dump_graphviz_dir_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TocoFlags::set_allocated_dump_graphviz_dir(std::string* dump_graphviz_dir) {
  if (dump_graphviz_dir != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  dump_graphviz_dir_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), dump_graphviz_dir);
  // @@protoc_insertion_point(field_set_allocated:toco.TocoFlags.dump_graphviz_dir)
}

// optional bool dump_graphviz_include_video = 25;
inline bool TocoFlags::_internal_has_dump_graphviz_include_video() const {
  bool value = (_has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline bool TocoFlags::has_dump_graphviz_include_video() const {
  return _internal_has_dump_graphviz_include_video();
}
inline void TocoFlags::clear_dump_graphviz_include_video() {
  dump_graphviz_include_video_ = false;
  _has_bits_[0] &= ~0x00040000u;
}
inline bool TocoFlags::_internal_dump_graphviz_include_video() const {
  return dump_graphviz_include_video_;
}
inline bool TocoFlags::dump_graphviz_include_video() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.dump_graphviz_include_video)
  return _internal_dump_graphviz_include_video();
}
inline void TocoFlags::_internal_set_dump_graphviz_include_video(bool value) {
  _has_bits_[0] |= 0x00040000u;
  dump_graphviz_include_video_ = value;
}
inline void TocoFlags::set_dump_graphviz_include_video(bool value) {
  _internal_set_dump_graphviz_include_video(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.dump_graphviz_include_video)
}

// optional bool post_training_quantize = 26 [default = false];
inline bool TocoFlags::_internal_has_post_training_quantize() const {
  bool value = (_has_bits_[0] & 0x00080000u) != 0;
  return value;
}
inline bool TocoFlags::has_post_training_quantize() const {
  return _internal_has_post_training_quantize();
}
inline void TocoFlags::clear_post_training_quantize() {
  post_training_quantize_ = false;
  _has_bits_[0] &= ~0x00080000u;
}
inline bool TocoFlags::_internal_post_training_quantize() const {
  return post_training_quantize_;
}
inline bool TocoFlags::post_training_quantize() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.post_training_quantize)
  return _internal_post_training_quantize();
}
inline void TocoFlags::_internal_set_post_training_quantize(bool value) {
  _has_bits_[0] |= 0x00080000u;
  post_training_quantize_ = value;
}
inline void TocoFlags::set_post_training_quantize(bool value) {
  _internal_set_post_training_quantize(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.post_training_quantize)
}

// optional bool enable_select_tf_ops = 27 [default = false];
inline bool TocoFlags::_internal_has_enable_select_tf_ops() const {
  bool value = (_has_bits_[0] & 0x00100000u) != 0;
  return value;
}
inline bool TocoFlags::has_enable_select_tf_ops() const {
  return _internal_has_enable_select_tf_ops();
}
inline void TocoFlags::clear_enable_select_tf_ops() {
  enable_select_tf_ops_ = false;
  _has_bits_[0] &= ~0x00100000u;
}
inline bool TocoFlags::_internal_enable_select_tf_ops() const {
  return enable_select_tf_ops_;
}
inline bool TocoFlags::enable_select_tf_ops() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.enable_select_tf_ops)
  return _internal_enable_select_tf_ops();
}
inline void TocoFlags::_internal_set_enable_select_tf_ops(bool value) {
  _has_bits_[0] |= 0x00100000u;
  enable_select_tf_ops_ = value;
}
inline void TocoFlags::set_enable_select_tf_ops(bool value) {
  _internal_set_enable_select_tf_ops(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.enable_select_tf_ops)
}

// optional bool force_select_tf_ops = 28 [default = false];
inline bool TocoFlags::_internal_has_force_select_tf_ops() const {
  bool value = (_has_bits_[0] & 0x00200000u) != 0;
  return value;
}
inline bool TocoFlags::has_force_select_tf_ops() const {
  return _internal_has_force_select_tf_ops();
}
inline void TocoFlags::clear_force_select_tf_ops() {
  force_select_tf_ops_ = false;
  _has_bits_[0] &= ~0x00200000u;
}
inline bool TocoFlags::_internal_force_select_tf_ops() const {
  return force_select_tf_ops_;
}
inline bool TocoFlags::force_select_tf_ops() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.force_select_tf_ops)
  return _internal_force_select_tf_ops();
}
inline void TocoFlags::_internal_set_force_select_tf_ops(bool value) {
  _has_bits_[0] |= 0x00200000u;
  force_select_tf_ops_ = value;
}
inline void TocoFlags::set_force_select_tf_ops(bool value) {
  _internal_set_force_select_tf_ops(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.force_select_tf_ops)
}

// optional bool quantize_to_float16 = 29 [default = false];
inline bool TocoFlags::_internal_has_quantize_to_float16() const {
  bool value = (_has_bits_[0] & 0x00400000u) != 0;
  return value;
}
inline bool TocoFlags::has_quantize_to_float16() const {
  return _internal_has_quantize_to_float16();
}
inline void TocoFlags::clear_quantize_to_float16() {
  quantize_to_float16_ = false;
  _has_bits_[0] &= ~0x00400000u;
}
inline bool TocoFlags::_internal_quantize_to_float16() const {
  return quantize_to_float16_;
}
inline bool TocoFlags::quantize_to_float16() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.quantize_to_float16)
  return _internal_quantize_to_float16();
}
inline void TocoFlags::_internal_set_quantize_to_float16(bool value) {
  _has_bits_[0] |= 0x00400000u;
  quantize_to_float16_ = value;
}
inline void TocoFlags::set_quantize_to_float16(bool value) {
  _internal_set_quantize_to_float16(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.quantize_to_float16)
}

// optional bool allow_dynamic_tensors = 30 [default = true];
inline bool TocoFlags::_internal_has_allow_dynamic_tensors() const {
  bool value = (_has_bits_[0] & 0x01000000u) != 0;
  return value;
}
inline bool TocoFlags::has_allow_dynamic_tensors() const {
  return _internal_has_allow_dynamic_tensors();
}
inline void TocoFlags::clear_allow_dynamic_tensors() {
  allow_dynamic_tensors_ = true;
  _has_bits_[0] &= ~0x01000000u;
}
inline bool TocoFlags::_internal_allow_dynamic_tensors() const {
  return allow_dynamic_tensors_;
}
inline bool TocoFlags::allow_dynamic_tensors() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.allow_dynamic_tensors)
  return _internal_allow_dynamic_tensors();
}
inline void TocoFlags::_internal_set_allow_dynamic_tensors(bool value) {
  _has_bits_[0] |= 0x01000000u;
  allow_dynamic_tensors_ = value;
}
inline void TocoFlags::set_allow_dynamic_tensors(bool value) {
  _internal_set_allow_dynamic_tensors(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.allow_dynamic_tensors)
}

// optional string conversion_summary_dir = 31;
inline bool TocoFlags::_internal_has_conversion_summary_dir() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TocoFlags::has_conversion_summary_dir() const {
  return _internal_has_conversion_summary_dir();
}
inline void TocoFlags::clear_conversion_summary_dir() {
  conversion_summary_dir_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& TocoFlags::conversion_summary_dir() const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.conversion_summary_dir)
  return _internal_conversion_summary_dir();
}
inline void TocoFlags::set_conversion_summary_dir(const std::string& value) {
  _internal_set_conversion_summary_dir(value);
  // @@protoc_insertion_point(field_set:toco.TocoFlags.conversion_summary_dir)
}
inline std::string* TocoFlags::mutable_conversion_summary_dir() {
  // @@protoc_insertion_point(field_mutable:toco.TocoFlags.conversion_summary_dir)
  return _internal_mutable_conversion_summary_dir();
}
inline const std::string& TocoFlags::_internal_conversion_summary_dir() const {
  return conversion_summary_dir_.GetNoArena();
}
inline void TocoFlags::_internal_set_conversion_summary_dir(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  conversion_summary_dir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TocoFlags::set_conversion_summary_dir(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  conversion_summary_dir_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:toco.TocoFlags.conversion_summary_dir)
}
inline void TocoFlags::set_conversion_summary_dir(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  conversion_summary_dir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:toco.TocoFlags.conversion_summary_dir)
}
inline void TocoFlags::set_conversion_summary_dir(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  conversion_summary_dir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:toco.TocoFlags.conversion_summary_dir)
}
inline std::string* TocoFlags::_internal_mutable_conversion_summary_dir() {
  _has_bits_[0] |= 0x00000002u;
  return conversion_summary_dir_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TocoFlags::release_conversion_summary_dir() {
  // @@protoc_insertion_point(field_release:toco.TocoFlags.conversion_summary_dir)
  if (!has_conversion_summary_dir()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return conversion_summary_dir_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TocoFlags::set_allocated_conversion_summary_dir(std::string* conversion_summary_dir) {
  if (conversion_summary_dir != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  conversion_summary_dir_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), conversion_summary_dir);
  // @@protoc_insertion_point(field_set_allocated:toco.TocoFlags.conversion_summary_dir)
}

// repeated string custom_opdefs = 32;
inline int TocoFlags::_internal_custom_opdefs_size() const {
  return custom_opdefs_.size();
}
inline int TocoFlags::custom_opdefs_size() const {
  return _internal_custom_opdefs_size();
}
inline void TocoFlags::clear_custom_opdefs() {
  custom_opdefs_.Clear();
}
inline std::string* TocoFlags::add_custom_opdefs() {
  // @@protoc_insertion_point(field_add_mutable:toco.TocoFlags.custom_opdefs)
  return _internal_add_custom_opdefs();
}
inline const std::string& TocoFlags::_internal_custom_opdefs(int index) const {
  return custom_opdefs_.Get(index);
}
inline const std::string& TocoFlags::custom_opdefs(int index) const {
  // @@protoc_insertion_point(field_get:toco.TocoFlags.custom_opdefs)
  return _internal_custom_opdefs(index);
}
inline std::string* TocoFlags::mutable_custom_opdefs(int index) {
  // @@protoc_insertion_point(field_mutable:toco.TocoFlags.custom_opdefs)
  return custom_opdefs_.Mutable(index);
}
inline void TocoFlags::set_custom_opdefs(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:toco.TocoFlags.custom_opdefs)
  custom_opdefs_.Mutable(index)->assign(value);
}
inline void TocoFlags::set_custom_opdefs(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:toco.TocoFlags.custom_opdefs)
  custom_opdefs_.Mutable(index)->assign(std::move(value));
}
inline void TocoFlags::set_custom_opdefs(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  custom_opdefs_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:toco.TocoFlags.custom_opdefs)
}
inline void TocoFlags::set_custom_opdefs(int index, const char* value, size_t size) {
  custom_opdefs_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:toco.TocoFlags.custom_opdefs)
}
inline std::string* TocoFlags::_internal_add_custom_opdefs() {
  return custom_opdefs_.Add();
}
inline void TocoFlags::add_custom_opdefs(const std::string& value) {
  custom_opdefs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:toco.TocoFlags.custom_opdefs)
}
inline void TocoFlags::add_custom_opdefs(std::string&& value) {
  custom_opdefs_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:toco.TocoFlags.custom_opdefs)
}
inline void TocoFlags::add_custom_opdefs(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  custom_opdefs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:toco.TocoFlags.custom_opdefs)
}
inline void TocoFlags::add_custom_opdefs(const char* value, size_t size) {
  custom_opdefs_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:toco.TocoFlags.custom_opdefs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TocoFlags::custom_opdefs() const {
  // @@protoc_insertion_point(field_list:toco.TocoFlags.custom_opdefs)
  return custom_opdefs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TocoFlags::mutable_custom_opdefs() {
  // @@protoc_insertion_point(field_mutable_list:toco.TocoFlags.custom_opdefs)
  return &custom_opdefs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace toco

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::toco::FileFormat> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::toco::FileFormat>() {
  return ::toco::FileFormat_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tensorflow_2flite_2ftoco_2ftoco_5fflags_2eproto
